### PR TITLE
Update Payloads & Packets to readonly structs and pass by readonly ref

### PR DESCRIPTION
**Pull request by iamcarbon**
This PR updates the Packets and Payloads to readonly structures and passes them by readonly reference to reduce allocations.

### CODE REVIEW

**Comment by bgrainger** [comment]
Thanks! Marking all readonly structs as `readonly struct` is something I should have done once that was added to C# 7.2.

I'm requiring the [DCO](https://blog.chef.io/2016/09/19/introducing-developer-certificate-of-origin/) on contributions; the [instructions here](https://github.com/mysql-net/MySqlConnector/pull/553/checks?check_run_id=14162081) show how to fix the problem (by adding a signoff).

It's hard to tell from just looking at the source if this will be a net improvement or not. `in PayloadData` will be adding an extra layer of indirection (by passing that struct by reference, instead of simply copying it); in a lot of cases, the `ArraySegment` property will immediately be dereferenced (and copied). Will this be bad/good? I can't tell. Perhaps I can come up with a micro-benchmark that exercises one of these code paths and determines if there's an improvement.

**Comment by bgrainger** [comment]
Added a benchmark here: https://github.com/bgrainger/MySqlConnector/commit/ec1573b5837eb1be77ffc464a70a834e7a8a53a1

I tested `OkPayload`, which is very commonly created, but also already has an optimisation that reuses a cached value as much as possible.

The results don't immediately indicate that the changes in this PR are a net win. For reusing a cached `OkPayload`, the current code (`BaselineCached`) is still the best. I suspect that the overhead of copying a full struct (instead of just an object reference) is significant enough that the `readonly struct` approach is less optimal overall. You can see this most clearly by comparing `StructSpan` vs `ClassSpan`, where the only difference is whether a `readonly struct` or a `sealed class` is returned; `ClassSpan` is usually faster, even when it's allocating.

Method |       Job | Runtime |     Toolchain | Categories |     Mean |     Error |    StdDev |    StdErr |      Min |       Q1 |   Median |       Q3 |      Max |         Op/s | Scaled |  Gen 0 | Allocated |
----------------- |---------- |-------- |-------------- |----------- |---------:|----------:|----------:|----------:|---------:|---------:|---------:|---------:|---------:|-------------:|-------:|-------:|----------:|
BaselineCached |    net472 |     Clr |  CsProjnet472 |     Cached | 53.50 ns | 0.3884 ns | 0.3633 ns | 0.0938 ns | 52.91 ns | 53.16 ns | 53.46 ns | 53.74 ns | 54.09 ns | 18,692,368.4 |   1.00 |      - |       0 B |
ReadonlyCached |    net472 |     Clr |  CsProjnet472 |     Cached | 56.52 ns | 0.1396 ns | 0.1306 ns | 0.0337 ns | 56.27 ns | 56.42 ns | 56.50 ns | 56.63 ns | 56.72 ns | 17,692,648.6 |   1.06 |      - |       0 B |
StructSpanCached |    net472 |     Clr |  CsProjnet472 |     Cached | 55.80 ns | 0.2056 ns | 0.1923 ns | 0.0496 ns | 55.49 ns | 55.69 ns | 55.81 ns | 55.92 ns | 56.20 ns | 17,921,566.8 |   1.04 |      - |       0 B |
ClassSpanCached |    net472 |     Clr |  CsProjnet472 |     Cached | 51.66 ns | 0.1141 ns | 0.0953 ns | 0.0264 ns | 51.47 ns | 51.59 ns | 51.65 ns | 51.69 ns | 51.86 ns | 19,359,137.3 |   0.97 |      - |       0 B |
|           |         |               |            |          |           |           |           |          |          |          |          |          |              |        |        |           |
BaselineNew |    net472 |     Clr |  CsProjnet472 |        New | 59.00 ns | 0.4797 ns | 0.4252 ns | 0.1136 ns | 58.04 ns | 58.88 ns | 58.95 ns | 59.17 ns | 59.83 ns | 16,948,516.0 |   1.00 | 0.0075 |      48 B |
ReadonlyNew |    net472 |     Clr |  CsProjnet472 |        New | 56.75 ns | 0.1117 ns | 0.1045 ns | 0.0270 ns | 56.58 ns | 56.65 ns | 56.78 ns | 56.84 ns | 56.93 ns | 17,621,724.5 |   0.96 |      - |       0 B |
StructSpanNew |    net472 |     Clr |  CsProjnet472 |        New | 56.90 ns | 0.2413 ns | 0.2257 ns | 0.0583 ns | 56.58 ns | 56.70 ns | 56.91 ns | 57.06 ns | 57.36 ns | 17,574,633.6 |   0.96 |      - |       0 B |
ClassSpanNew |    net472 |     Clr |  CsProjnet472 |        New | 57.66 ns | 0.2455 ns | 0.2050 ns | 0.0569 ns | 57.25 ns | 57.51 ns | 57.72 ns | 57.77 ns | 58.03 ns | 17,342,910.5 |   0.98 | 0.0076 |      48 B |
|           |         |               |            |          |           |           |           |          |          |          |          |          |              |        |        |           |
BaselineCached | netcore21 |    Core | .NET Core 2.1 |     Cached | 32.31 ns | 0.1672 ns | 0.1396 ns | 0.0387 ns | 32.01 ns | 32.24 ns | 32.32 ns | 32.40 ns | 32.58 ns | 30,947,096.4 |   1.00 |      - |       0 B |
ReadonlyCached | netcore21 |    Core | .NET Core 2.1 |     Cached | 33.88 ns | 0.1086 ns | 0.0963 ns | 0.0257 ns | 33.76 ns | 33.78 ns | 33.86 ns | 33.95 ns | 34.08 ns | 29,515,361.5 |   1.05 |      - |       0 B |
StructSpanCached | netcore21 |    Core | .NET Core 2.1 |     Cached | 37.24 ns | 0.1091 ns | 0.0911 ns | 0.0253 ns | 37.08 ns | 37.19 ns | 37.22 ns | 37.31 ns | 37.42 ns | 26,850,602.8 |   1.15 |      - |       0 B |
ClassSpanCached | netcore21 |    Core | .NET Core 2.1 |     Cached | 23.71 ns | 0.0990 ns | 0.0878 ns | 0.0235 ns | 23.59 ns | 23.64 ns | 23.71 ns | 23.78 ns | 23.89 ns | 42,171,481.3 |   0.73 |      - |       0 B |
|           |         |               |            |          |           |           |           |          |          |          |          |          |              |        |        |           |
BaselineNew | netcore21 |    Core | .NET Core 2.1 |        New | 36.82 ns | 0.1648 ns | 0.1461 ns | 0.0390 ns | 36.63 ns | 36.67 ns | 36.83 ns | 36.91 ns | 37.08 ns | 27,157,806.3 |   1.00 | 0.0076 |      48 B |
ReadonlyNew | netcore21 |    Core | .NET Core 2.1 |        New | 34.12 ns | 0.2931 ns | 0.2288 ns | 0.0661 ns | 33.77 ns | 33.95 ns | 34.11 ns | 34.34 ns | 34.44 ns | 29,304,464.4 |   0.93 |      - |       0 B |
StructSpanNew | netcore21 |    Core | .NET Core 2.1 |        New | 37.11 ns | 0.1673 ns | 0.1483 ns | 0.0396 ns | 36.96 ns | 37.00 ns | 37.07 ns | 37.18 ns | 37.46 ns | 26,948,212.5 |   1.01 |      - |       0 B |
ClassSpanNew | netcore21 |    Core | .NET Core 2.1 |        New | 28.84 ns | 0.1782 ns | 0.1580 ns | 0.0422 ns | 28.59 ns | 28.70 ns | 28.84 ns | 28.97 ns | 29.08 ns | 34,676,340.4 |   0.78 | 0.0076 |      48 B |

**Comment by iamcarbon** [comment]
@bgrainger Thanks for benchmarking this and providing some more context.

If we're already caching the classes in common cases, I don't think the allocation reduction will be worth the additional overhead. Boo.

I'll see if I can find any specific cases that will benefit from this and issue a new PR with benchmarks if I find any notable wins.

**Comment by bgrainger** [comment]
I did update the structs to `readonly struct`, since there's no reason not to; thanks for the heads-up: 20717e226643fd4d089e1acd3b376bcd95fa3b47

**Pull request closed without merging**
