### PR TITLE
Added support of ADO.NET "ReservedWords" collection schema (used for …

### PR DESCRIPTION
**Pull request by fedesasso**
Hi there. Hi added support of "ReservedWords" ADO.NET collection schema (see issue #375 "Support more schema collections in GetSchema").
Since I didn't find much in the official docs, I gathering the full list from what returned by the ODBC provider.
I needed that to make MySqlConnector work with NHibernate.

### CODE REVIEW

**Comment by bgrainger** [comment]
The hard-coded list of reserved words for MySQL 5.7 is here: https://dev.mysql.com/doc/refman/5.7/en/keywords.html

This list includes entries, such as `ABSOLUTE` and `ADA` that aren't on that list.

For MySQL 8.0, the [`INFORMATION_SCHEMA.KEYWORDS`](https://dev.mysql.com/doc/refman/8.0/en/keywords-table.html) table could be used to load the list at runtime.

**Comment by bgrainger** [comment]
I dumped the results of `select word from information_schema.keywords where reserved = 1;` on MySQL Server 8.0.12 in https://gist.github.com/bgrainger/54e7f3200772734855b08970792f0175.

This should be the most up-to-date list of reserved words that can be hard-coded in the connector.

**Comment by bgrainger** [comment]
There's a bug (in 8.0.12 and earlier) that could make it impractical to query `INFORMATION_SCHEMA.KEYWORDS` at runtime: https://bugs.mysql.com/bug.php?id=90160

**Comment by fedesasso** [comment]
Were it not for the annoying bug, I'd SELECT VERSION(); parse somehow the result string and if it were )> 8.0 I'd query the information_schema_keywords table, otherwise use a hard coded list.
Since the mysql bug there, the hard coded list seems the viable solution, regardless the db version (even if different versions would likely have different lists).

Do you want me to change the code to use the list you provided, and then make a new pull request, or do find it quicker to change the code on your own, since I guess you already are on it?
(sorry, I'm new to github workflows)

**Comment by bgrainger** [comment]
> I'd SELECT VERSION(); parse somehow the result string and if it were )> 8.0

The problem with that is that MariaDB 10.0 is only compatible with MySQL 5.6 (but has a higher version number).

> Do you want me to change the code to use the list you provided, and then make a new pull request

Yes; just push a new commit to this PR (instead of opening a new PR).

**Pull request merged**
