### PR TITLE
Avoid culture aware comparisons and a string allocation

### PR DESCRIPTION
**Pull request by iamcarbon**
The standard string == operator is a culture aware comparison. Updating these to "is" makes these culture invariant.

This PR removes the few instances of these.

It also removes a single string allocation when checking for HasDelimiter. There are also a few other opportunities to avoid string allocations if we raise our minimum target to NET461 (ideally NET462).

### CODE REVIEW

**Comment by bgrainger** [comment]
> The standard string == operator is a culture aware comparison.

I'm extremely skeptical of this claim; do you have proof?

**Comment by bgrainger** [comment]
[`==` and `is`](https://sharplab.io/#v2:EYLgtghglgdgNAFxFANgHwAICYCMBYAKAwGYACbUgYVIG9DSHyzgB7FlUgWRwAoMcADKQDOASlr1GUjAHYRpALwLSAIhYwApioDckhgF89TUq3ZcsfQSPF0CU6XOGkoTlQgDuLHUcMF9QA==) look identical to me.

**Comment by bgrainger** [comment]
> It also removes a single string allocation when checking for HasDelimiter. 

Thanks. Can you reduce the PR down to just this one change?

**Comment by iamcarbon** [comment]
@bgrainger Totally right, == and is operates are both do ordinal (case-sensitive and culture-insensitive) comparisons! Thanks for double checking the source generation too -- I've updated my knowledge!

I've posted a single clean PR for the single allocation reduction.

**Pull request closed without merging**
