### PR TITLE
Try/catch ResetConnectionAsync (works around #208)

### PR DESCRIPTION
**Pull request by bnabholz**
When the ConnectionPool is asked for a session, depending on server version, it will attempt to reauthenticate.  On occasion the server will close the connection and the next read from the stream will be 0 bytes, causing the connection to fail.  This PR wraps ResetConnectionAsync in a try/catch, and if it throws it will fall back to instantiating a new MySqlSession.

I'm not sure if we should be trying to catch only certain exceptions (EndOfStreamException?) and let others bubble up as usual.

### CODE REVIEW

**Comment by bgrainger** [comment]
> I'm not sure if we should be trying to catch only certain exceptions (EndOfStreamException?) and let others bubble up as usual.

I generally prefer to catch the specific exception I know I'm handling; however, in this case it seems good to fall back to creating a new session if any kind of `IOException` or `SocketException` is thrown.

**Comment by bgrainger** [comment]
I'm going to update the code I just pushed to only catch `EndOfStreamException`, `IOException`, `SocketException` (same as `TryPingAsync`); I don't want other programming errors to be masked by this `catch` handler (as it would dramatically reduce performance by essentially disabling connection pooling).

**Comment by bnabholz** [comment]
Sounds good to me.  Thanks for reviewing and thanks to you and the other contributors for this project!

**Comment by bgrainger** [comment]
Shipped in [0.26.4](https://www.nuget.org/packages/MySqlConnector/0.26.4); thanks for the contribution!

**Pull request merged**
