### PR TITLE
Handle missing metadata

### PR DESCRIPTION
**Pull request by trejjam**
Solve #1398

### CODE REVIEW

**Comment by bgrainger** [comment]
Thanks; I think this makes sense to accommodate a "truncated" packet sent from the server as though it doesn't actually support `MARIADB_CLIENT_CACHE_METADATA`. (A packet capture to show exactly what's going on would still be interesting.)

Do you agree that these contributions are made under the terms of https://developercertificate.org/? (I can set that check to pass.)

**Comment by trejjam** [comment]
ToC approve

**Comment by trejjam** [comment]
I hope here is the problematic select: The issue is with 2. column, 1. has metadata
[problematic-select.zip](https://github.com/mysql-net/MySqlConnector/files/13430729/problematic-select.zip)

**Comment by trejjam** [comment]
[mysql-missing-metadata.zip](https://github.com/mysql-net/MySqlConnector/files/13430805/mysql-missing-metadata2.zip)

**Pull request merged**
