### PR TITLE
Add support for reading certificates from the Certificate Store

### PR DESCRIPTION
**Pull request by hajekj**
Related issue: #536

### CODE REVIEW

**Comment by hajekj** [comment]
Looks like the Travis CI has failed from the confusion of closing and reoping (fixed the DCO signoff message through force push). Could anyone re-run the Travis task?

**Comment by bgrainger** [comment]
It looks like a build is running here (but is failing): https://travis-ci.org/mysql-net/MySqlConnector/builds/408604934

Pushing a fix for the bug should start a new build.

**Comment by hajekj** [comment]
I have the tests working now except for this one - https://ci.appveyor.com/project/mysqlnet/mysqlconnector/build/1.0.1538#L509 which appears to fail due to the command taking too long to process?

**Comment by bgrainger** [comment]
Sorry, that's an intermittent spurious build failure that's unrelated to your code; I'll rebuild it till it passes.

**Comment by hajekj** [comment]
The last error the test ended with (https://ci.appveyor.com/project/mysqlnet/mysqlconnector/build/1.0.1539#L647) - doesn't seem to occur in Travis CI or on my Windows machine. Any idea what could be causing it?

**Comment by bgrainger** [comment]
The "baseline" test is failing, so congratulations: you found a bug in Connector/NET. 😀

The [Connector/NET documentation](https://dev.mysql.com/doc/connector-net/en/connector-net-connection-options.html) says it supports `Certificate Thumbprint`, but [the code](https://github.com/mysql/mysql-connector-net/blob/68c54371821c87ff40a773acc127ce357b46a5ae/Source/MySql.Data/MySqlConnectionStringBuilder.cs#L112) actually has `certificate thumb print`.

Let's support all three options: `CertificateThumbprint`, `Certificate Thumbprint`, `Certificate Thumb Print` and change the test to `certificate thumb print`.

**Comment by bgrainger** [comment]
Thanks a lot for this contribution! I'll squash and merge it once the build passes.

**Pull request merged**
