### PR TITLE
Reset connection on return to pool

### PR DESCRIPTION
**Pull request by bgrainger**
Issue #178 suggests that the connection be reset when it's returned to the pool, so that it's ready immediately when a new `MySqlConnection` is opened (and reuses a pooled connection).

In the current PR, the connection is reset synchronously when the session is closed; this may not be sufficient to increase performance since the caller will still be blocked (albeit at the end of the connection lifetime, not at the beginning). It may be necessary to offload the work of resetting the connection to a background thread.

### CODE REVIEW

**Comment by caleblloyd** [comment]
This is an interesting proposition. I'll do some review and performance testing on it tomorrow.

**Comment by caleblloyd** [comment]
Use of Synchronous I/O in this method is correct.  Switching the Connection Reset to Async causes lock-ups when using Sync I/O.

I think that awaiting the result of the Connection Reset should be deferred until the connection is drawn from the pool again.  Since connections are inserted at the back of the Queue, this should give it a nice amount of time to complete before it is drawn again.

While we're at it - the `TryPingAsync` command really only needs to be run after a certain amount of idle time (say 30 seconds).  If the connection has been active in a short period of time, this is pretty much a wasted round trip.

I pushed a branch with a commit on top of this PR that has this behavior: https://github.com/mysql-net/MySqlConnector/commit/518c72cacc4beaf0adafbb7073cc7a0e29c00b5e you should be able to cherry-pick that commit into this PR if it looks good.

**Comment by caleblloyd** [comment]
I think this will unintentionally fix #169 because the exception in `ResetConnectionAsync` will get caught and the MySqlSession will be disposed.  It will mask that exception every single time, I'm not sure if that's a good thing...

**Comment by bgrainger** [comment]
As I wrote on #178:

> The downside would be that any errors would be silently ignored and only manifest themselves as a performance problem (because the pool would never contain live connections).

I also don't currently have a good idea for handling this.

Were you able to do any performance testing on this yet, to see if the change is worthwhile?

**Comment by caleblloyd** [comment]
> I also don't currently have a good idea for handling this.

If we want to mirror the current behavior, we could still initiate the reset task upon returning, but check for an exception upon re-drawing from the pool.  It would essentially be [removing this try-catch](https://github.com/mysql-net/MySqlConnector/commit/5313c564239b22c60eb0474439f01ec9112c560e#diff-709a9503470224e906bdecb8736e16c4R122)

> Were you able to do any performance testing on this yet, to see if the change is worthwhile?

The main benefit here would be for clients which exhibit behaviors:

(A) Connection pool is not constantly in use
(B) There is a high Round Trip Time (RTT) between Client and Server

Looking at our current traffic for drawing from the connection pool, we have 3 round trips:

image

RT 1 is from `PingSessionAsync`.  This takes RTT + 0.07ms
RT 2 is from actual resetting of the connection.  This takes RTT + 0.06ms
RT 3 is from `SET NAMES utf8mb4`.  This takes RTT + 0.06ms

If the connection pool is constantly in use, there will be no difference whether connection is reset at the beginning or end because those events will occur back-to-back.  If there is a negligible RTT (e.g. localhost like my timings here), then all of this will  happen in a fraction of a millisecond.  But, if (A) and (B) are both true, then we will move 2 of the 3 Round Trips when leasing a connection to a time when the connection would normally be idle, and that will benefit clients with a high RTT.

One thing to consider is that by implementing this, we would now  be forcing these 2 round trips over Sync I/O, which will block a thread pool thread.  I don't think we force Sync I/O on any other happy paths in the codebase currently.

Another consideration might be to run `ResetConnectionAsync` in the place of `PingSessionAsync`, and catch a MySqlException in the case that the connection was closed by the server.  This would eliminate one round trip.

**Comment by caleblloyd** [comment]
As a follow-up to my most recent comment.

> One thing to consider is that by implementing this, we would now be forcing these 2 round trips over Sync I/O, which will block a thread pool thread. I don't think we force Sync I/O on any other happy paths in the codebase currently.

After reflecting on this a little more, I think that staying 100% async on the happy path should be the primary concern of our library.

> Another option is to run `ResetConnectionAsync` in the place of `PingSessionAsync`, and catch a MySqlException in the case that the connection was closed by the server.  This would eliminate one round trip.

This is still an option but would mask errors in `ResetConnectionAsync` by catching the exception.  It would have to be done by parsing exception messages.  If everyone else agrees, my vote is to abandon this PR and open this change as an "up for grabs" issue.

**Comment by bgrainger** [comment]
Closing in favour of #264.

**Pull request closed without merging**
