### PR TITLE
Make table alias accessible from MySqlDbColumn

### PR DESCRIPTION
**Pull request by AlexKerman**
This PR make table alias accessible in data reader.
Ref #1521

### CODE REVIEW

**Comment by bgrainger** [comment]
Thanks for the contribution! I'll take a look soon. (Mostly just want to see if there's precedent in other ADO.NET providers.)

It would be good to include some tests for this new behaviour.

**Comment by bgrainger** [comment]
Npgsql adds a `TableOID` property: https://github.com/npgsql/npgsql/blob/32eb7097c81e3dc6e3cdc59c2f19592883f00c77/src/Npgsql/Schema/NpgsqlDbColumn.cs#L199-L202

SqlClient doesn't appear to have public `DbColumn`-derived type.

**Comment by bgrainger** [comment]
Thanks for the contribution!

**Comment by AlexKerman** [comment]
> Thanks for the contribution!

Thank you for your research. It very useful for me because I doing postgres support for my tool. Unfortunately I don't know how to test this properly. I had researched test for ProviderType field and didn't fount out how to insert test for my field corectly.

**Pull request merged**
